version: '3'

services:
  app:
    # image: my-expo-app:v2
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run tunnel

