services:
  app:
    # image: myplg-app:latest
    build: ./frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    # command: npx expo start
    command: tail -f /dev/null